version: '3'
services:
  web:
    build: .
    ports:
      - "80:5000"
    environment:
#      - HOST=131.1.252.119
      - HOST=neo4j
      - NEO4J_USERNAME=neo4j
      - ENV NEO4J_PASSWORD=password
      - ENV max_nodes=10000
  neo4j:
    image: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
      - "7473:7473"
    environment:
      - dbms.memory.pagecache.size=2GB
      - dbms.memory.heap.max_size=16GB
      - dbms.memory.heap.initial_size=8GB

    volumes:
      - ./neo4j_data:/var/lib/neo4j/data

