version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
  neo4j:
    image: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
      - "7473:7473"
    volumes:
      - ./neo4j_data:/var/lib/neo4j/data

